### PR TITLE
Fixes #21

### LINKED ISSUE #21: Brightness with setBrightness: 0 brightest and 255 darkest
If i set the brightness with the setBrightness-function from neopixel.py to 0, the leds are very bright and if i set it to 255, they are very dark. Is this a problem with my LED-Stripe (ws2812b) or did anyone else noticed this too and the doc-string should be modified?

### PR DESCRIPTION
**Pull request by Thor77**
Modify doc-string of setBrightness

### CODE REVIEW

**Comment by tdicola** [comment]
Are you sure you don't need to invert the signal when talking to your LED string?  When I added setBrightness function it wasn't behaving like you mention--a value of 0 was off and 255 was full bright.  I'll give it a test again since some stuff has changed since then, but double check your LEDs aren't inverted.  

A quick test is to send an explicit 255, 255, 255 pixel and a 0, 0, 0 pixel (don't do any brightness changes, just write those pure color values out).  The 255 pixel should be bright white and the 0 pixel should be completely off.

**Comment by Thor77** [comment]
`255, 255, 255` is full bright and `0, 0, 0` is full dark, but this setBrightness-function is really strange,
if i run this code:
```python
def color_brightness(color, brightness):
    all_pixels(strip, strip.setPixelColor, color)
    strip.setBrightness(brightness)
    strip.show()
brightness = 255
while brightness >= 0:
    print(brightness)
    color_brightness(color, brightness)
    brightness -= 5
    time.sleep(0.05)
time.sleep(1)
while brightness <= 255:
    print(brightness)
    color_brightness(color, brightness)
    brightness += 5
    time.sleep(0.05)
```
My LEDs are first full bright (like it should be), then they get darker and darker, but when the brightness-value increases again they dont get brighter again, but first a little bit lighter and then darker and darker until off.

**Comment by tdicola** [comment]
Oh you're hitting a quantization quirk with the code.  It's kind of a side
effect of using a similar implementation as the Arduino code for
setBrightness.  The issue is instead of scaling each pixel color as its
being clocked out (which is really tough when you have strict timing
constraints like here) we scale the entire buffer ahead of time.  A side
effect of this is, if you scale all the way down to 0 then applying a scale
to that it doesn't really have any effect because scaling 0 by anything is
still 0.  Try changing your code to only really scale from 255 down to 1
(or 5 in this case).

**Comment by Thor77** [comment]
I changed my script to this:
```python
def color_brightness(color, brightness):
    all_pixels(strip, strip.setPixelColor, color)
    strip.setBrightness(brightness)
    strip.show()
brightness = 255
while brightness > 5:
    print(brightness)
    color_brightness(color, brightness)
    brightness -= 5
    time.sleep(0.05)
    time.sleep(1)
while brightness <= 255:
    print(brightness)
    color_brightness(color, brightness)
    brightness += 5
    time.sleep(0.05)
```
But it's still the same behaviour, it looks like this:
https://www.dropbox.com/s/f4ce7yvlf8t1yw8/VID_20150124_210726.mp4?dl=0

**Comment by jgarff** [comment]
This should no longer be needed.  Please see the following last issue comment:

https://github.com/jgarff/rpi_ws281x/issues/21

**Pull request closed without merging**
