### PR TITLE
Added Makefile. Compile without additional frameworks

### PR DESCRIPTION
**Pull request by cyphunk**
While scons may have advantages, some may appreciate being able to compile without internet to install scons framework.

### CODE REVIEW

**Comment by jgarff** [comment]
Sorry, but I'd really rather not have to support two different build environments and keep them consistent.

**Comment by cyphunk** [comment]
yeah I can understand that. Is there something special provided by scons though? Genuinely curious.

**Comment by jgarff** [comment]
SCons has much better automatic dependency tracking, parallel build handling, and is based on python, a real language.  I also like the environment and builders concept used by SCons.

I used make for years, and have built many projects with it, but in the end I find SCons much more flexible and capable, especially for large projects.  Most systems include python as well, which is the only requirement for SCons.

**Comment by cyphunk** [comment]
good to know. i'll check it out on the next project I have that needs it. thanks

**Pull request closed without merging**
