### PR TITLE
added Ctrl-C handler to turn off all LEDs on exit

### PR DESCRIPTION
**Pull request by s8mlu**
I didn't like leaving the LEDs in random state when exit.

### CODE REVIEW

**Comment by Duwacell** [comment]
Working, Thanks !

**Comment by Frodox** [comment]
ping @jgarff :)

**Comment by jgarff** [comment]
Thanks for the pull request.  Some people however like to leave the LEDs set when the program exits.  This is already a optional feature on the test program.  Please see the -c command line option for the C test.  If you added a command line option to the strandtest.py script, I'd be happy to take it.  Thanks.

**Comment by s8mlu** [comment]
added -c option, please review, thanks.

**Pull request merged**
