### PR TITLE
Better error return codes for ws2811_init + gamma correction

### PR DESCRIPTION
**Pull request by Gadgetoid**
I'm submitting this PR as a way to keep track of how far I'm straying from the rpi_ws281x codebase with my suggestions. Don't merge quite yet ;)

This PR currently includes gamma correction, which I feel everyone could benefit from, but which may require a more flexible implementation to allow for different gamma curves for different devices and, ideally, even different colour channels.

Of particular interest, however, are the return codes, aimed at making it easier to diagnose a failure from `ws2811_init`. These are my primary proposed change, and I'd appreciate any feedback on the implementation/style and anything that matters. 

Cheers!

### CODE REVIEW

**Comment by sschroe** [comment]
For the return codes i've been thinking of using an enum rather than defines. This makes it more clear what values can be expected (anything from the enum). Additionally i used a macro list to also define some descriptive strings that can be used by the implementating application.

This should give you an rough idea of what it would look like:
```
#define WS2811_RETURN_STATES(X)                                                         \
            X(WS2811_SUCCESS, "Success"),                                               \
            X(WS2811_ERROR_GENERIC, "Generic failure"),                                 \
            X(WS2811_ERROR_OUT_OF_MEMORY, "Out of memory"),                             \
            X(WS2811_ERROR_BAD_HARDWARE, "Hardware revision is not supported"),         \
            X(WS2811_ERROR_MEM_LOCK, "Memory lock failed"),                             \
            X(WS2811_ERROR_MMAP, "mmap() failed"),                                      \
            X(WS2811_ERROR_MAP_REGISTERS, "Unable to map registers into userspace"),    \
            X(WS2811_ERROR_GPIO_INIT, "Unable to initialize GPIO"),                     \
            X(WS2811_ERROR_PWM_SETUP, "Unable to initialize PWM"),                      \
            X(WS2811_ERROR_MAILBOX_DEVICE, "Failed to create mailbox device"),          \
            X(WS2811_ERROR_DMA, "DMA error")                                            \

#define WS2811_RETURN_STATES_ENUM(name, str) name
#define WS2811_RETURN_STATES_STRING(name, str) str

typedef enum ws2811_return_state {
    WS2811_RETURN_STATES(WS2811_RETURN_STATES_ENUM),
    
    WS2811_RETURN_STATE_COUNT
} ws2811_ret_state;

ws2811_ret_state ws2811_init(ws2811_t *ws2811);                         //< Initialize buffers/hardware
...
const char * ws2811_get_ret_state_str(const ws2811_ret_state state);    //< Get string representation of the given return state
```

Downside is that it does not use negative values and its somewhat more complex i guess. Which solution is better i'm not sure about though.

A few things i'd suggest for your implementation:

- Add an `WS2811_SUCCESS` type. Seems more fitting than checking against 0 for this particular case while using defines/enums for all others.
- `ws2811_render` and `ws2811_wait` should use error codes too for consistency.

Completely besides that i'd suggest splitting your changes into several pull requests (hw types, gamma, return codes). Makes it much easier to review and merge individually :)

**Comment by Gadgetoid** [comment]
Thank you for your feedback, this was just the sort of input I was fishing for ;)

I'm a little wary of creating a breaking change, although with no knowledge of how people other than myself are using this library, I'm not so sure if my concerns are founded. And I suppose code that depends upon the old "-1 for all the things" approach isn't all that hard to change!

I find your solution elegant, and the use of an explicit return type, complete with descriptive text, could be far more useful for achieving my goal of debugging this library in the field.

As a bit of background, we use this library (or a slightly modified version with gamma correction in fact) as the back-end for Unicorn HAT, I have two goals:

1. Push some better return codes upstream so when the library fails to initialize, it's abundantly clear why
2. Rationalize the gamma correction tweak, so I no longer have to maintain a modified version of the library

These are as much for my own goals as for sanity's sake- I wish to split rpi_ws281x out of our UnicornHAT GitHub repository and rely on the original code instead.

We also hold the keys to https://pypi.python.org/pypi/rpi_ws281x, which contains a modified variant of this codebase, and thus could be prone to raising some support headaches for all of us.

I'd like the python package index version to represent *this* codebase.

**Comment by sschroe** [comment]
Well the compatibility could be retained by adding a value field to the macro list and just manually specifying the values for each type. This way we'd have negative values still and old code should continue to function without any changes.

Alternatively gcc's `__COUNTER__` define could be used. Though i don't really like this as there doesn't seem to be a way to be certain of its starting value (i.e if it was used in one of the headers before).

The strings could even be further enhanced to include additional variables (like the dma error code). Though this would require keeping some string buffer around internally along with some snprintf's.
Only depends on how far we want to go with this :)

As for the gamma... what is the actual purpose of it? Is the map based on a logarithmic scale to make the brightness changes appear more consistent? If so its certainly nice to have, though it should be optional rather than being always used.

**Comment by Gadgetoid** [comment]
> As for the gamma... what is the actual purpose of it? Is the map based on a logarithmic scale to make the brightness changes appear more consistent? If so its certainly nice to have, though it should be optional rather than being always used.

The 0-255 brightness ranges on most of these LEDs (if not all) map directly to PWM values, and not to any real concept of brightness. The gamma table is used to gain a brightness curve that looks more sensible to the human eye.

Adafruit explain this a bit better than me; https://learn.adafruit.com/led-tricks-gamma-correction/the-issue

Brightness doesn't match terribly well across colours either, so it might be sensible to have an optional, per colour channel, gamma correction table.

You can see the effect of wonky brightness if you, for example, cycle through 360 degrees of the HSV colour space at full brightness and saturation. The result will be a light that appears to get dimmer and brighter as it passes through certain colours. I don't think most people care or notice, but for those who do then gamma correction is a great feature to have for both correcting brightness and colour accuracy problems.

Dithering is another trick used to try and solve similar problems. By quickly toggling the lights on and off at low brightness values, you gain additional steps of brightness control and can fill the low end of the range. Normally the brightness levels are far from smooth, and go from Off to Bright and then right into OH GOD MY EYES!

Here's a good example of the latter: https://youtu.be/1-_JtRl2ks0?t=6

**Comment by Gadgetoid** [comment]
Closing since this has been dealt with in: https://github.com/jgarff/rpi_ws281x/pull/119

I will raise gamma correction as another PR when I can come up with a reasonable way to include it.

**Pull request closed without merging**
