### PR TITLE
Add install target in SConscript

### PR DESCRIPTION
**Pull request by KoltesDigital**

### CODE REVIEW

**Comment by Bloutiouf** [comment]
Hm, maybe *ws281x* is a better name for the include directory.

BTW the lib name is still ws2811, shouldn't it be ws281x?

**Comment by penfold42** [comment]
Good question - what do we call it if my sk6812 support is merged ?

Led-1wire ?

**Comment by Bloutiouf** [comment]
Well the ws281x is still the parent of some variations. IHMO it makes sense to keep the name ws281x, as it clearly states what the lib is about. But if the lib is to support variations, the Readme should mention it. See https://github.com/cpldcpu/light_ws2812 which does the same.

I made the remark about the lib name because the repo name is rpi_ws281x, it'd be logical for the lib the have the same name.

**Comment by jgarff** [comment]
Thanks for the pull request.  Before this goes in, I'm thinking that it would be nice if the install path could be overridden from the command line in a similar way to the verbose flag to SCons.  For example:

scons V=1 INSTALL_PREFIX=/usr/local

Would you be willing to make this change first?  If not, I can bring it into a branch and make the necessary changes instead.  Thanks.

**Comment by Bloutiouf** [comment]
It makes sense, I'll do it.

**Comment by jgarff** [comment]
I'm going to close this pull request as nothing has happened with it for a while.  Please re-open if you'd like to resubmit.  Thanks.

**Pull request closed without merging**
