### PR TITLE
Pi Zero W v1.1 support added to rpihw.c

### PR DESCRIPTION
**Pull request by Gadgetoid**
Title says it all, really! Happy IoTing.

### CODE REVIEW

**Comment by tavalin** [comment]
I've tested the PR on my Pi Zero W and it works. Any chance on getting the PR merged?

**Comment by Boeeerb** [comment]
Tested here also and confirm working on this PR

**Comment by tavalin** [comment]
@jgarff any reason this hasn't been merged but a more recent PR on the same file has?

**Comment by Gadgetoid** [comment]
I'm unaware of Revision ID `0x9200c1` and it's not documented at http://elinux.org/RPi_HardwareHistory - yet it's been merged into `rpihw.c` as "Pi Zero W". This is not the Revision ID reported by the Zero Ws that we distribute. Albeit it could be a pre-release that I haven't come across, or a later release that hasn't trickled down yet, but it's still not the Revision ID used by the vast majority of Pi Zeros that I'm aware of.

I've got to toss my hat in the ring here. Why in the world was the demonstrably incorrect #164 merged and not my launch day PR with the correct Revision ID for the Zero W?

```
pi@zerowstem:~ $ cat /proc/cpuinfo
processor       : 0
model name      : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS        : 697.95
Features        : half thumb fastmult vfp edsp java tls
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xb76
CPU revision    : 7

Hardware        : BCM2708
Revision        : 9000c1
Serial          : 000000006e4fa20b
```

**Comment by electrokean** [comment]
@Gadgetoid Based on the other Rev IDs listed on elinux.org it would seem that 0x9200c1 may be a board manufactured by Embest/Farnell, rather than Sony

**Comment by penfold42** [comment]
Can we merge this please ?

I need to get Hyperion packages rebuilt with support for both zero W revisions

Thanks.

**Comment by jgarff** [comment]
As always, I appreciate your pull request.  Sorry, it looks like this fix was previously merged.  I'm going to close this request as a duplicate.  Thanks.

**Comment by tavalin** [comment]
@jgarff why have you closed this? There are apparently two variants of the Pi Zero so this PR should still be valid.

**Comment by tavalin** [comment]
Nevermind just noticed there was yet another PR for Pi Zero.

**Pull request closed without merging**
