### PR TITLE
Pwm pcm spi

### PR DESCRIPTION
**Pull request by tvoverbeek**
Added PCM and SPI support.
Correct mode selected depending on selected gpionum.
No changes in API. Python examples work as they are after rebuilding the extension.

### CODE REVIEW

**Comment by sschroe** [comment]
Looks quite interesting! One thing i'd find quite interesting to know is the differences between these modes (apart from the GPIO pin). For example what is the maximum amount of leds that i can control with each of these and what other impacts are there (CPU usage etc). This might also make an interesting point for the README.

In `ws2811.h` you changed the value of `WS2811_ERROR_DMA`. If possible i'd suggest to keep the previous value and to append `WS2811_ERROR_ILLEGAL_GPIO` to the end of the list instead.

**Comment by tvoverbeek** [comment]
Will restore WS2811_ERROR_DMA to its original value.
Am on travel now so cannot change and test it till the end of next week (Begin December).
Both PWM and PCM use DMA transfers (means no CPU involvement for the transfer).
Max DMA transfer length is 65536 bytes. For PWM this has to cover 2 led strands, for PCM only one. With 12 bytes per LED (4 colors, 8 symbols per color, 3 bits per symbol) this means approximately 5400 LEDs for a single strand in PCM and 2700 LEDs per string for PWM.
I suppose you'll never reach the max due to the power needed and signal degradation.
SPI uses the SPI device driver in the kernel. For transfers larger than 96 bytes the kernel driver also uses DMA.
So I expect all three variants to be very similar in CPU load.
More after I am back from travel.

**Comment by Gadgetoid** [comment]
Thrilled to see this in PR form now! Thank you for this @tvoverbeek it brings a satisfying conclusion to the "how can I use neopixels with analog audio" question we've been answering tentatively for years now!

**Comment by penfold42** [comment]
Great work - I was only expecting some consideration for a spi mode in the code so I could come in an add the guts of it.

Top work!

**Comment by tvoverbeek** [comment]
Corrected Error Codes (New ones at the end, DMA_ERROR back to its original value).
Added some theoretical limits and practical cpu usage figures to README.md
Squashed all commits for the push request into one.

**Comment by jgarff** [comment]
Great work!  I know this pull request has been outstanding for a couple weeks.  I'm hoping to get it tested this weekend for inclusion.  Thanks again!

**Comment by jgarff** [comment]
Given the size and significance of the changeset, I decided to create dev branch so it could be tested more thoroughly by a broader audience before merging to the mainline.  Just in case there are further changes, I changed the version in this changeset to 1.1.0 instead of 2.0.0.  I'd like to treat the 1.1.0 version as a pre-release numbering for 2.0.0.  We can update to 2.0.0 once this has been tested more broadly and any other resulting changes are applied.  Thanks again for all the work, it's much appreciated!

At this point, I'd like to invite everyone to start using the dev branch and let us know if there are any issues.  Thanks.

**Comment by tvoverbeek** [comment]
Any news about merging the dev branch with the main branch?
Anybody tested the pcm and spi support?

**Pull request closed without merging**
