### PR TITLE
Add distinct error codes with string representations

### PR DESCRIPTION
**Pull request by sschroe**
Heres my approach for adding distinct error codes for the function return states. The enum values are negative so existing code should work unchanged.

`ws2811_get_return_t_str` can be used to get the descriptive error strings (as done in the example). Maybe there a better suggestions for the function name though... :)

### CODE REVIEW

**Comment by Gadgetoid** [comment]
Excellent! I didn't find the time to resubmit my PR with your suggestions, but I will gladly yield to this one and give it my vote. This change is very much needed!

I'll pull down and build it now, I think I have a Unicorn HAT somewhere I can try the code with.

**Comment by Gadgetoid** [comment]
I'd recommend also adding the error response text to the Python code in `neopixel.py` in the `begin` method at line 102. The code might be changed to something like:

```python
resp = ws.ws2811_init(self._leds)
if resp != 0:
    message = ws.ws2811_get_return_t_str(resp)
    raise RuntimeError('ws2811_init failed with code {0} ({1})'.format(resp, message))
```

**Comment by sschroe** [comment]
Going to be away the next two days but i'll have a look at it after :)

**Comment by sschroe** [comment]
Added changes for the python stuff.

**Pull request merged**
