### PR TITLE
Add revision code for CM4 8 GB Lite WiFi

### PR DESCRIPTION
**Pull request by timonsku**

### CODE REVIEW

**Comment by timonsku** [comment]
@Gadgetoid if you could merge this one too that would be great. It seem the revision codes might actually only change with RAM, rest so far seems to be the same, so this should technically be the last one for CM4 for now.

**Comment by Gadgetoid** [comment]
Done! Sorry for the delay. Taking it on faith that you know what you're doing since I have absolutely no way to verify this!

Do we need to petition for you to be a maintainer, too? :laughing:

**Comment by timonsku** [comment]
Thanks!
I think there won't be much more until maybe the CM5 comes out :)
But we probably should get back to that fix that would make adding these unnecessary in the future.

**Comment by oodev17** [comment]
Dear supporters,

I am trying to run this lib (1.1.7 from nuget) on a CM4 Lite 4GB NO-Wifi and I am getting 

_WS281xException: An Error occurred while initializing - Hardware revision is not supported (-3)
at rpi_ws281x.WS281x..ctor(Settings settings)
   at Program.Main(String[] args) in C:\Workspace\.......\Program.cs:line 26_


From /proc/cpuinfo I see:
```
Hardware	: BCM2711
Revision	: c03140
Serial		: 100000006d7d8718
Model		: Raspberry Pi Compute Module 4 Rev 1.0

```

What could be the reason?
Thank you in advance

**Pull request merged**
