### PR TITLE
Added support for Raspberry Pi 4B V1.4 4GB and 8GB

### PR DESCRIPTION
**Pull request by ZhiJGuo**
Added support for Raspberry Pi 4B v1.4 4GB and 8GB. Raspberry Pi 4B 8GB V1.2 version does not exist, only V1.4

### CODE REVIEW

**Review by cp2004 — APPROVED** [review]
Verified that these changes work, tested by a user of my project [OctoPrint WS281x LED Status](https://github.com/cp2004/OctoPrint-WS281x_LED_Status). All was ok, it didn't work, I patched (using this as a base) and it worked by manually updating the dependency for them.
👍

**Comment by cp2004** [comment]
@Gadgetoid @jgarff is there any word on when PRs will get merged? I am depending on this library in a reasonably popular plugin. I have the changes implemented manually to work around, but would love it if it could be merged - it would make life simpler here.

Thank you for the consideration, this library has made a lot of cool things possible.

**Comment by Gadgetoid** [comment]
Thank you both. Sorry for the delay. A mixture of lockdown and moving house has made it necessary for me to focus my workflow and a lot of things have been left by the wayside.

**Comment by cp2004** [comment]
Thank you! Great timing too - I had planned this week to fork the stuff here and try and use the patched version in the next release of my project, hopefully now I can just update the dependency version. Thanks for what you're doing here 😄

**Pull request merged**
