### PR TITLE
fix: Added some new CM4 modules

### PR DESCRIPTION
**Pull request by Laurix1983**
It seems that these new CM4 modules are popping up now and this list has to be modified. I got the latest order couple of weeks ago so here is my 5 cents in case these have not been spotted by someone else ;-)

### CODE REVIEW

**Comment by pluxr** [comment]
Hi, I havent been able to solve this.

I have added the details of my CM4 board to the .c file but I keeo getting the hardware error when importing neopixel.

It would be grat to know how to manage this issue. Thanks

**Comment by pluxr** [comment]
@Laurix1983

**Comment by Laurix1983** [comment]
Are you sure you are adding the right hardware releases. It seems that there is a myriad of different releases of rpi cm4 popping up so this list of definitions will grow quite a lot


There was another github thread (I will try to find it when I am at my computer) which had good steps to check needed values from procinfo.

**Comment by pluxr** [comment]
> Are you sure you are adding the right hardware releases. It seems that there is a myriad of different releases of rpi cm4 popping up so this list of definitions will grow quite a lot
> 
> 
> There was another github thread (I will try to find it when I am at my computer) which had good steps to check needed values from procinfo.

Yes. I have the right info for my board however I keep getting the same error code.

Thank you.

**Comment by mookie-** [comment]
Thank you @Laurix1983 for this PR.

It helped me get this running on my board:

```
Hardware        : BCM2835
Revision          : d03141
Model              : Raspberry Pi Compute Module 4 Rev 1.1
```

I would be happy if this could get merged :)

**Comment by onewheelskyward** [comment]
This would have saved me a bunch of time.

**Pull request merged**
