### PR TITLE
Python3 compatibility

### PR DESCRIPTION
**Pull request by emlyn**
Since #153 failed on Python 2.7 on some installs (because `future` is not installed), I'm resubmitting with `future` added as a dependency. This should fix it for Python 2.7.
Although it would be possible to code around this without adding a dependency, I think this is the cleanest way, and it may be useful for any other Python 2/3 issues that crop up later.
If you'd prefer not to add a dependency, I'd be happy to change this to use the other workaround, so just let me know.

### CODE REVIEW

**Comment by Frodox** [comment]
bump

**Comment by Gadgetoid** [comment]
I'm aiming to deprecate this Python code in favour of rpi_ws281-python, in which I've already tackled this issue. However I seem to have lost the spread operator on `pos.indices(self.size)` and am concerned this constitutes a bug in my code.

See: https://github.com/rpi-ws281x/rpi-ws281x-python/blob/4db1d93f34beed5563cf8f55f1ef9b91b92987eb/library/rpi_ws281x/rpi_ws281x.py#L30

Do you have any examples of LED_Data usage that might demonstrate this?

**Comment by emlyn** [comment]
I have some code that I think would be broken by that:
```python
    def solid(self, colour):
        n = self.leds.numPixels()
        self.leds.setPixelColor(slice(0, n), [colour]*n)
        self._display()
```
Where `self.leds` is a `Adafruit_NeoPixel` instance. It would be easy enough to work around with a loop though.

**Comment by jlu5** [comment]
Another dependency free solution might be something like https://github.com/jlu5/rpi_ws281x/commit/d7cbfdb23acd9ce7bf7c1a69449f3ecc907b65c7, which checks for the Python version and maps `xrange` to `range` on Python 3.

**Comment by Gadgetoid** [comment]
I've merged this into the Python bindings using @emlyn's Sonic Pixels code as a test case. See: https://github.com/rpi-ws281x/rpi-ws281x-python/commit/75f4b6425e523a364a62524223d99ce53623ae76

**Pull request closed without merging**
